### PR TITLE
Tarea 10: Guess the movie

### PR DESCRIPTION
**Pull request by juanpablo-lopez01**

### CODE REVIEW

**Comment by emolinaglobant** [comment]
@juanpablo-lopez01 , where did you got this approach there are other students using the exact same

**Comment by juanpablo-lopez01** [comment]
> For this activity I had some difficulties, so I investigated the approach of my colleagues and after understanding how their approach worked I used it as a reference to carry out the logic of the game

**Comment by juanpablo-lopez01** [comment]
> > For this activity I had some difficulties, so I investigated the approach of my colleagues and after understanding how their approach worked I used it as a reference to carry out the logic of the game

If I am making a mistake I apologize, I could try the development of the activity again

**Comment by emolinaglobant** [comment]
@juanpablo-lopez01 , nope its fine, remember you can't do the same for the final project

**Review by emolinaglobant — APPROVED** [review]

**Pull request merged**
